config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :users
  resources :articles
  resources :news
  resources :requests
  resources :concert_reviews #do i need this?

   root 'welcome#index'

  get 'login', to: 'sessions#new', as: 'login'

  get 'signup', to: 'users#new', as: 'signup'

  get 'reviews', to: 'articles#reviews', as: 'reviews'

  get 'critics', to: 'articles#index', as: 'critics'

  get 'autocomplete_artist', to: 'articles#autocomplete_artist', as: 'autocomplete_artist'

  get 'autocomplete_album', to: 'articles#autocomplete_album', as: 'autocomplete_album'

  get 'articles/:id/approve' => 'articles#approve', as: :articles_approve

  get 'articles/:id/deny' => 'articles#deny', as: :articles_deny

  get 'concert_reviews/:id/approve' => 'concert_reviews#approve', as: :concert_reviews_approve
    get 'concert_reviews/:id/deny' => 'concert_reviews#deny', as: :concert_reviews_deny

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :artist
	belongs_to :album 
	validates :author, :content, :rating, presence: true

scope :search_by, -> (search_term) { joins('INNER JOIN artists ON articles.artist_id = artists.id  INNER JOIN albums ON articles.album_id = albums.id').where("artists.name ilike ? or albums.title ilike ? or articles.author ilike?", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%").order("articles.created_at DESC") }

	#scope :search_by, -> (search_term) { joins('INNER JOIN artists ON articles.artist_id = artists.id  INNER JOIN articles.album_id = albums.id').where("articles.title ilike ? or artists.name ilike ? or albums.title ilike ?", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%").order("artists.created_at DESC") }


#read ! http://guides.rubyonrails.org/active_record_querying.html#joining-tables
#read ! http://www.w3schools.com/sql/sql_join.asp
#read ! http://www.w3schools.com/sql/sql_join_inner.asp

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

def index
       # @item_album_artwork = @itunes.music("#{@track.artist} #{@track.title}").results.first.artwork_url100
	if params[:search] && (Article.search_by(params[:search]).count != 0) 
		@articles = Article.search_by(params[:search]).sort_by { |obj| obj.rating }
		@articles.reverse!
	else
		@articles = Article.order(updated_at: :desc)
	end

	if params[:search] && (ConcertReview.search_by(params[:search]).count != 0)
		@concertreviews = ConcertReview.search_by(params[:search])
	else
		@concertreviews = ConcertReview.order(updated_at: :desc)
	end

	#this won't work well because article and concert reviews may not be approved at all.
	feed = Article.last(5) + ConcertReview.last(5)
	feed.delete_if {|obj| obj.approval != true }
 	feed = feed.sort_by {|obj| obj.updated_at}
 	feed = feed.reverse!
 	@feed = feed.first(4)



end


def autocomplete_artist
  @artists = Artist.search_by(params[:term])
  json_array = []
  @artists.each do |a|
  	json_array << {:id => a.id, :label => "#{a.id} - #{a.name}", :value => a.name }
  end
  render json: json_array
end

def autocomplete_album
  @albums = Album.search_by(params[:term])
  json_array = []
  @albums.each do |a|
  	json_array << {:id => a.id, :label => "#{a.id} - #{a.title}", :value => a.title }
  end
  render json: json_array
end	


def new
	@article = Article.new
	@album = Album.new
	@artist = Artist.new
	
	

end

def create
	@album = Album.new(album_params)
	@album.title = @album.title.split.map(&:capitalize).join(' ').rstrip.lstrip
	
	@artist = Artist.new(artist_params)
	@artist.name = @artist.name.split.map(&:capitalize).join(' ').rstrip.lstrip

	#save artist into database
	if(Artist.where(:name => @artist.name).count == 0) 
		@artist.save
	else
		@artist = Artist.where(:name => @artist.name)[0]
	end

	#save album into database
	if (Album.where(:title => @album.title).count == 0)
		@album.artist = @artist
		@album.save
	else
		@album = Album.where(:title => @album.title)[0]
	end

	@article = Article.new(article_params)

	if (@article.save)
		#UserMailer.written_article.deliver	
		@article.artist = @artist
		@article.album = @album
		@article.save
		redirect_to root_path, notice: 'Your Article is Pending for Review.  An email will be conveyed if we think it is right for our site!'
	else
		render "new"
	end
end

def show
	@article = Article.find(params[:id])
	render layout: false

end

def edit
		@article = Article.find(params[:id])
		if session[:user_id] == nil
			redirect_to root_path, notice: "No Access Rights"
		end
	
		
		#return RedirectToAction("Index", model);

		#@article = Article.find(params[:id])
		
end

def reviews
    render layout: false
end


def update
		@article = Article.find(params[:id])
		if (session[:user_id])
			if @article.update(article_params)
				@article.save
				redirect_to root_path, notice: 'Article is Online'
			else
				render "edit"
			end
		else
			redirect_to @article, notice: "No Access Rights"
			
		end
end

def approve
	@article = Article.find(params[:id])
		if (session[:user_id])
			@article.approval = true;
			@article.save
			#UserMailer.article_email(@article.email).deliver
			redirect_to root_path, notice: 'Article is Online'
		else
			redirect_to @article, notice: "No Access Rights"
		end
end

def deny
	@article = Article.find(params[:id])
		if (session[:user_id])
			@article.approval = false;
			@article.save 
			redirect_to root_path, notice: 'Article has been taken Offline'
		else
			redirect_to @article, notice: 'No Access Rights'
		end
end

def destroy
        @article = Article.find(params[:id])   
       	if session[:user_id]
       		@article.delete
       		redirect_to action: "index"
       	else
			redirect_to @article, notice: "No Access Rights"
       	end
  end


private

def article_params
	params.require(:article).permit(:author, :email, :content, :image, :artist_ids, :album_ids, :rating)
end



def album_params
	params.require(:album).permit(:title, :genre, :year)
end

def artist_params
	params.require(:artist).permit(:name)
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_advertise.html.erb
<% if @feed.count != 0 %>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @feed.each do |news| %>
    <li data-target="#carousel-example-generic" data-slide-to="0"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
  

    <% article = @feed.first %>

    <div class="item active" style="height: 300px; z-index: 10">
    <center><img src= <%= @feed.first.image %> style="height: 300px; text-align: right;"></center> 
      <div class="carousel-caption" style="text-align: right">
      <% article = @feed.first %>
      <% if @feed.first.has_attribute?("album_id") %>
      <a href= "<%= article_path(article) %>" class="ajax_link">
        <h1><mark>"<%= @feed.first.album.title %>"</mark></h1>
        <h2><mark><%= @feed.first.artist.name %></mark></h2>
        <h3><mark>Written by <%= @feed.first.author %></mark></h3>
        <p><mark><%= truncate(@feed.first.content, length: 200) %></mark></p>
      </a>

      <% else %>

      <a href= "<%= concert_review_path(article) %>" class="ajax_link">
        <h1><mark><%= @feed.first.title %> AHH"</mark></h1>
        <h2><mark><%= @feed.first.artist.name %></mark></h2>
        <h3><mark>Written by <%= @feed.first.author %></mark></h3> 
        <p><mark><%= truncate(@feed.first.content, length: 200) %></mark></p>
      </a>

      <% end %>
      </div>   
      </div>
   

    

    <% @feed.delete_at(0) %>

    <% @feed.each do |article| %>
    <div class="item" style="z-index: 10">
      <center><img src=<%=article.image%> style="height: 300px"></center>
      <div class="carousel-caption" style="text-align: right">
      <% if article.has_attribute?("album_id") %>
      <a href= "<%= article_path(article) %>" class="ajax_link">
      	<h1><mark>"<%= article.album.title %>"</mark></h1>
      	<h2><mark><%= article.artist.name %></mark></h2>
      	<h3><mark>Written by <%= article.author %></mark></h3>
        <p><mark><%= truncate(article.content, length: 200) %></mark></p>
      </a>
      <% else %>
      <a href= "<%= concert_review_path(article) %>" class="ajax_link">
        <h1><mark>"<%= article.title %>"</mark></h1>
        <h2><mark><%= article.artist.name %></mark></h2>
        <h3><mark>Written by <%= article.author %></mark></h3> 
        <p><mark><%= truncate(article.content, length: 200) %></mark></p>
        <% end %>
      </a>
      </div>
    </div>
    <% end %>
   </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev" style="z-index: 20">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next" style="z-index: 20">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <div class="control-group">
   
   <div class="col-lg-6">

    <%= f.label :Critic %>
    <div class="controls">
    <%= f.text_field :author, class: "form-control" %>
    </div>

    <%= f.label :email %>
    <div class="controls">
    <%= f.text_field :email, class: "form-control" %>
    </div>
  

  <% if @article.new_record? %>
    <%= f.label :artist %>
    <div class="controls">
      <%= text_field(:artist, :name, :class => "form-control") %>
    </div>
    
    <%= f.label :album %>
    <div class="controls">
      <%= text_field(:album, :title, :class => "form-control") %>
    </div>

    <%= f.label :album %> Genre
    <div class="controls">
      <%= text_field(:album, :genre, :class => "form-control") %>
    </div>
    
    <%= f.label :year %> Released
    <div class="controls">
      <%= number_field(:album, :year, :class => "form-control") %>
    </div>

    <% end %>


    <%= f.label :rating %> 0 to 10
    <div class="controls"> 
          <%= f.number_field :rating, :in => 0.0..10.0, class: "form-control" %>
    </div>

    <%= f.label :image %> URL
    <div class="controls">
    <%= f.text_field :image, class: "form-control" %>
    </div>
  
   </div>

  <div class="col-lg-6">
    <div class="control-group">
      <%= f.label :content %>
      <div class="controls">
        <%= f.text_area :content, rows: "22", cols: "50", class: "form-control" %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-lg-12">
    <div class="form-actions">
    <br />
    <center>
    <%= f.submit nil, class: "btn btn-primary" %>
    <%= link_to 'Cancel', articles_path, class: "btn btn-primary" %>
    </center>
    </div>
    </div>





  </div>


<% end %>

app/views/articles/edit.html.erb
<h1><% @article = Article.find(params[:id]) %></h1>
	<%= render :partial => 'form' %>

app/views/articles/new.html.erb
<script type="text/javascript">
  $(document).ready(function() {
  $('.ajax_link').click(function(event) {
  event.preventDefault();
  var url = $(this).attr('href');
  $.get(url, function(htmloutput) {
  $('#article_show').html(htmloutput);
  $('#modal_article').modal('show');
  });

  });
  })
</script>

<div class="modal fade" id="modal_article" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
  
  <div class="modal-body">
  <div id="article_show"></div>
  </div>
  
  <div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
  
  </div>
  </div>
</div>


<script>
$(document).ready(function() {

 $("#album_title").autocomplete({
  source: "/autocomplete_album",
  minLength: 2,
  select: function( event, ui ) {
  //alert(ui.item.id + " " + ui.item.value);
  }
  });


  $("#artist_name").autocomplete({
  source: "/autocomplete_artist",
  minLength: 2,
  select: function( event, ui ) {
  //alert(ui.item.id + " " + ui.item.value);
  }
  });



});
</script>

<%= render :partial => 'form' %> 

app/views/articles/reviews.html.erb
	<div class= "row">
  		<center><a href="/concert_reviews/new"><button type="button" class="btn btn-default lg" style="width: 90%"><h2>Submit a Concert Review</h2></button></a></center>
	</div>
	<br />

	<div class="row">
	<center>
  		<a href="/articles/new"><button type="button" class="btn btn-default lg" style="width: 90%"><h2>Submit an Album Review</h2></button></a>
  		</center>
	</div>

app/views/articles/show.html.erb
<%- model_class = Article -%>

<img src = <%= @article.image %> width= 250px style="float: left; border: solid transparent 7px">

<div class="page-header"> <h2><%= @article.album.title%></h2> <em><h3><%= @article.artist.name %></h3></em> Reviewed By <strong><%= @article.author %></strong></div>

<dl class="dl-horizontal">

<%= simple_format(@article.content.gsub(/\n/, '<br/>')) %>
<br />
<center>Grade - <%= @article.rating %> </center>
</dl>