config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :users
  resources :articles
  resources :news
  resources :requests
  resources :concert_reviews #do i need this?

   root 'welcome#index'

  get 'login', to: 'sessions#new', as: 'login'

  get 'signup', to: 'users#new', as: 'signup'

  get 'reviews', to: 'articles#reviews', as: 'reviews'

  get 'critics', to: 'articles#index', as: 'critics'

  get 'autocomplete_artist', to: 'articles#autocomplete_artist', as: 'autocomplete_artist'

  get 'autocomplete_album', to: 'articles#autocomplete_album', as: 'autocomplete_album'

  get 'articles/:id/approve' => 'articles#approve', as: :articles_approve

  get 'articles/:id/deny' => 'articles#deny', as: :articles_deny

  get 'concert_reviews/:id/approve' => 'concert_reviews#approve', as: :concert_reviews_approve
    get 'concert_reviews/:id/deny' => 'concert_reviews#deny', as: :concert_reviews_deny

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  respond_to :html, :xml, :json


  def index
  	list_songs
    @request = Request.new

  @newsfeed = Article.last(5) + News.last(5) + ConcertReview.last(5) #merges two tables 
  @newsfeed = @newsfeed.sort_by {|obj| obj.updated_at}
  @newsfeed = @newsfeed.last(15).reverse!




=begin -> higher efficiency but drawbacks in that a set of 3 news and 2 articles even if the 3rd article came before one of the 3 news and vice versa
   count = Article.count - 1
    @newsfeed = News.last(3)

    stopper = 0;

    while count >= 0 
      review = Article.all.sort[count]
      if review.approval == true
        @newsfeed.push(review)
        stopper = stopper + 1
      end
      if stopper == 2
        break
      end
      count = count - 1
    end

    @newsfeed = @newsfeed.sort_by { |obj| obj.updated_at }
    @newsfeed.reverse!
=end

    if request.xhr?
      render partial: "refresh"
    else
      render "index"
    end

  end


  def list_songs
  	@item = Scrobbler::User.new('reganhsu').recent_tracks.first
    #@item_ucla = Scrobbler::User.new('uclaradio').recent_tracks.first
    @itunes = ITunes::Client.new    

    @recent_tracks = Track.order(updated_at: :desc).limit(10)

  if @item != nil
    @track = Track.new({"title" => @item.name, 
              "artist" => @item.artist,
              "album" => @item.album})

    #@track_ucla = Track.new({"title" => @item_ucla.name, "artist" => @item_ucla.artist,"album" => @item_ucla.album})
    
    if(@track.artist.include? "amp;")
      @track.artist = @track.artist.delete "amp;"
    end
    
    if(@track.title.include? "amp;")
      @track.title = @track.title.delete "amp;"
    end

    if (Track.last != nil)
      if (@track.title != Track.last.title || @track.artist != Track.last.artist)
        @track.save!
      end
    end

    @item_album_artwork = @itunes.music("#{@track.artist} #{@track.title}").results
    @item_array_size = @item_album_artwork.size

    #@item_album_artwork_ucla = @itunes.music("#{@track_ucla.artist} #{@track_ucla.title}").results
    #@item_array_size_ucla = @item_album_artwork_ucla.size
  else
    @track = Track.last
  end

    @time = Time.new.to_i

    if Track.count != 0 #resetting the database for tracks warrants this - if/else statement
      @allowed_time = Track.last.created_at.to_i + 360
    else
      @allowed_time = @time
    end


    #@item_album_artwork_ucla = @itunes.music("#{@track_ucla.artist} #{@track_ucla.title}").results
    #@item_array_size_ucla = @item_album_artwork_ucla.size

  	 #respond_with(@item)
  	
  end





end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_button.html.erb
<style>
#dynamicheight
{
    width: 80%;
    
    /* Just for looks: */
    background-color: cornflowerblue;
    margin-top: 40px;
    z-index: -5;
    position: relative;
    border-radius: 100%;
    background-image: url(<%= asset_path 'vinyl.png' %>)
}
</style>

<script>
$(function() {
    var div = $('#dynamicheight');
    var width = div.width();
    
    div.css('height', width);
});
</script>



<center>
<button onclick="myFunction()" class="play_border" style="margin-left: auto; margin-right: auto; background-color: transparent;">


<center>
<div id = "refreshable" >
<%= render :partial => 'refresh' %>
</div>

</center>


    <!--padding top : how far the text is from the border of the disc -->





</button>

</center>

app/views/welcome/_player.html.erb
//wikipedia click image play stuff

app/views/welcome/_refresh.html.erb
<% if @allowed_time > @time %>
<!-- Regan's Radio Show -->
    <div id = "box" style="margin-left: auto; margin-right: auto">
      <center> <mark> "<%= @track.title %>" </mark></center>
    </div>

    <% if @item_array_size != 0 %>
        <center><img src=<%= @item_album_artwork.first.artwork_url100 %> style = "height: 160px; border-radius: 100%; border: white solid 10px"></center>
    <% end %>
  

      <center><mark><strong><%=@track.artist %></strong></mark></center>

      <% else %>
        <center><div id = "DJicon"><%= image_tag("press.svg") %></div></center>
      <% end %>

app/views/welcome/index.html.erb
<!-- Refreshing the Currently Playing -->
<script>
function makeAjaxCall() {

  $.get(document.URL, function(resp) { 
  $('#refreshable').html(resp);
 });
}



$(document).ready(function() {

  setInterval(function(){ makeAjaxCall(); }, 5000);

   });

</script>


<!--Rotating the Vinyl -->
<script>
$(function() {
    var $elie = $("#spin"), degree = 0, timer;
    rotate();
    function rotate() {
        
        $elie.css({ WebkitTransform: 'rotate(' + degree + 'deg)'});  
        $elie.css({ '-moz-transform': 'rotate(' + degree + 'deg)'});                      
        timer = setTimeout(function() {
            ++degree; rotate();
        },50);
    }

}); 




</script>

<style>

body {
    background-image: url(/assets/background2.png);
    background-size: 100%;
    background-repeat: no-repeat;
    background-attachment: fixed;


}

a:link
{
  color: black;
}
</style>


<!-- Showing Article as floating html-->
<script type="text/javascript">
  $(document).ready(function() {
  $('.ajax_link').click(function(event) {
  event.preventDefault();
  var url = $(this).attr('href');
  $.get(url, function(htmloutput) {
  $('#article_show').html(htmloutput);
  $('#modal_article').modal('show');
  });

  });
  });
</script>

<div class="modal fade" id="modal_article" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
  
  <div class="modal-body">
  <div id="article_show"></div>
  </div>
  
  <div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
  
  </div>
  </div>
</div>




<style>

#DJicon img
{
  height: 250px;
}

#title
{
  font-family: 'Permanent Marker', cursive !important
}
</style>


<link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>



    <div class="container">
    <div class ="row" style="color: white; font-size: 100px;">
    <center><div id = "title">UCLA RADIO</div></center>
        </div>

      <div class="row">

        <div class="col-lg-4">
          <div style="background-color:rgba(255, 255, 255, 0.8); text-align: right; height: 700px; border-radius: 10px; margin-top: 10px; border:  white 5px; padding-top: 5px;">
            <center><h2>What's New</h2></center>
            <% @newsfeed.each do |status| %>

            <!-- IF THE STATUS is an ALBUM review -->
              <% if status.has_attribute?("album_id")%>
              <centeR>
                <% if status.approval == true %>
                <a href= "<%= article_path(status) %>" class="ajax_link">
                  <h3><%= status.album.title %></h3>
                  <img src = <%= status.image %> width=200px> 
                  <h5 >Reviewed By <%= status.author %> </h5>
                  <h6><%= status.created_at.strftime(' %m/%d') %></h6>
                </a>
                <% end %>
                </centeR>

              <!-- IF SHOW review -->
              <%elsif  status.has_attribute?("location") %>
              <center>
                <% if status.approval == true %>
                <a href= "<%= concert_review_path(status) %>" class="ajax_link">
                  <h3><%= status.title %></h3>
                  <img src = <%= status.image %> width=200px> 
                  <h5>Reviewed By <%= status.author %> </h5>
                  <h6><%= status.created_at.strftime(' %m/%d') %></h6>
                </a>
                <% end %>
                </center>


              <!--IF PRESS RELEASE-->
              <% else %>
              <a href="<%= news_path(status) %>" class="ajax_link">
              <center>
              <div style=" background: -webkit-linear-gradient(top,#1eb2df, #17a7d2); color: white; box-shadow: 0px 3px 1px yellow, 0px -3px 1px yellow;">
                <h3> <%= status.title %></h3>
                <h6><%= status.created_at.strftime(' %m/%d') %></h6>
              </div>
              </center>
              </a>




              <% end %>
            <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->



        
<!--button for playing radio-->
<script>
function myFunction() {
    var myWindow = window.open("http://stream.uclaradio.com:8000/listen", "http://stream.uclaradio.com:8000/listen", "width=200, height=100");
}
</script>


<div class="col-lg-4">

<%= render :partial => 'button' %>


<div id = "request" style="margin-top: 20px"><center><%= render :partial => 'requests/form' %> </center></div>

</div>


<!-- Ucla's Radio


-->



      <div class="col-lg-4">
      <div style="background-color:rgba(255, 255, 255, 0.7); height: 700px; border-radius: 10px; margin-top: 10px; border: white 5px; padding: 5px">
            <center><h2>Recent Tracks</h2></center>
            <center>
            <table>
              <% @recent_tracks.each do |t|%>
                <tr><td><center> "<%=t.title%>" <b><%=t.artist %></b> <br /> <%= t.created_at.strftime('%l:%M %p %m/%d') %><br />  </center></td></tr>
              <% end %>
            </table>
            </center>
  
          </div>
        </div>
        </div>
      </div><!--/row-->


    </div> <!-- /container -->








<!-- <video controls="" height = "10" name="media"><source src="http://stream.uclaradio.com:8000/listen" type="audio/mpeg"></video> -->