config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :users
  resources :articles
  resources :news
  resources :requests
  resources :concert_reviews #do i need this?

   root 'welcome#index'

  get 'login', to: 'sessions#new', as: 'login'

  get 'signup', to: 'users#new', as: 'signup'

  get 'reviews', to: 'articles#reviews', as: 'reviews'

  get 'critics', to: 'articles#index', as: 'critics'

  get 'autocomplete_artist', to: 'articles#autocomplete_artist', as: 'autocomplete_artist'

  get 'autocomplete_album', to: 'articles#autocomplete_album', as: 'autocomplete_album'

  get 'articles/:id/approve' => 'articles#approve', as: :articles_approve

  get 'articles/:id/deny' => 'articles#deny', as: :articles_deny

  get 'concert_reviews/:id/approve' => 'concert_reviews#approve', as: :concert_reviews_approve
    get 'concert_reviews/:id/deny' => 'concert_reviews#deny', as: :concert_reviews_deny

end

app/controllers/concert_reviews_controller.rb
class ConcertReviewsController < ApplicationController
	def index
		
	end

def new
	@concertreview = ConcertReview.new
	@artist = Artist.new
	@artistNames = []
	artists = Artist.all
	artists.each do |artist|
		@artistNames.push(artist.name)
	end

end

def create
	
	@artist = Artist.new(artist_params)
	@artist.name = @artist.name.split.map(&:capitalize).join(' ').rstrip.lstrip

	if(Artist.where(:name => @artist.name).count == 0)
		@artist.save
	else
		@artist = Artist.where(:name => @artist.name)[0]
	end

	@concertreview = ConcertReview.new(concertreview_params)

	if (@concertreview.save)
		#UserMailer.written_article.deliver	
		@concertreview.artist = @artist
		@concertreview.save
		redirect_to root_path, notice: 'Your Article is Pending for Review.  An email will be conveyed if we think it is right for our site!'
	else
		render "new"
	end
end

def show
	@concertreview = ConcertReview.find(params[:id])
	render layout: false
end

def approve
	@concertreview = ConcertReview.find(params[:id])
		if (session[:user_id])
			@concertreview.approval = true;
			@concertreview.save
			#UserMailer.article_email(@concertreview.email).deliver
			redirect_to root_path, notice: 'Article is Online'
		else
			redirect_to @article, notice: "No Access Rights"
		end
end

def deny
	@concertreview = ConcertReview.find(params[:id])
		if (session[:user_id])
			@concertreview.approval = false;
			@concertreview.save 
			redirect_to root_path, notice: 'Article has been taken Offline'
		else
			redirect_to @concertreview, notice: 'No Access Rights'
		end
end


def edit
		@concertreview = ConcertReview.find(params[:id])
		if session[:user_id] == nil
			redirect_to root_path, notice: "No Access Rights"
		end
	
		
		#return RedirectToAction("Index", model);

		#@article = Article.find(params[:id])
		
end

def update
		@concertreview = ConcertReview.find(params[:id])
		if (session[:user_id])
			if @concertreview.update(concertreview_params)
				@concertreview.save
				redirect_to root_path, notice: 'Article is Online'
			else
				render "edit"
			end
		else
			redirect_to @concertreview, notice: "No Access Rights"
			
		end
end


def destroy
        @concertreview = ConcertReview.find(params[:id])   
       	if session[:user_id]
       		@concertreview.delete
       		redirect_to action: "index"
       	else
			redirect_to @concertreview, notice: "No Access Rights"
       	end
  end

private

def concertreview_params
	params.require(:concert_review).permit(:title, :author, :email, :content, :image, :location, :artist_id)
end



def artist_params
	params.require(:artist).permit(:name)
end
end

app/helpers/concert_reviews_helper.rb
module ConcertReviewsHelper
end

app/views/concert_reviews/_form.html.erb
<%= form_for @concertreview do |f| %>
  <div class="control-group">
   
   <div class="col-lg-6">

    <%= f.label :Title %>
    <div class="controls">
    <%= f.text_field :title, class: "form-control" %>
    </div>

    <%= f.label :Critic %>
    <div class="controls">
    <%= f.text_field :author, class: "form-control" %>
    </div>

    <%= f.label :Venue %>
    <div class="controls">
    <%= f.text_field :location, class: "form-control" %>
    </div>

    <%= f.label :email %>
    <div class="controls">
    <%= f.text_field :email, class: "form-control" %>
    </div>
  

    <%= f.label :artist %>
    <div class="controls">
      <input class = "form-control" id = "artists" <%= text_field(:artist, :name) %>
    </div>
    

    <%= f.label :image %> URL
    <div class="controls">
    <%= f.text_field :image, class: "form-control" %>
    </div>
  
   </div>

  <div class="col-lg-6">
    <div class="control-group">
      <%= f.label :content %>
      <div class="controls">
        <%= f.text_area :content, rows: "22", cols: "50", class: "form-control" %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-lg-12">
    <div class="form-actions">
    <br />
    <center>
    <%= f.submit nil, class: "btn btn-primary" %>
    <%= link_to 'Cancel', concert_reviews_path, class: "btn btn-primary" %>
    </center>
    </div>
    </div>





  </div>




<% end %>

app/views/concert_reviews/edit.html.erb
<h1><% @concertreview = ConcertReview.find(params[:id]) %></h1>
	<%= render :partial => 'form' %>

app/views/concert_reviews/new.html.erb
<head>
 <script type="text/javascript">
  $(document).ready(function() {
  $('.ajax_link').click(function(event) {
  event.preventDefault();
  var url = $(this).attr('href');
  $.get(url, function(htmloutput) {
  $('#article_show').html(htmloutput);
  $('#modal_article').modal('show');
  });

  });
  })
</script>

<div class="modal fade" id="modal_article" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
  
  <div class="modal-body">
  <div id="article_show"></div>
  </div>
  
  <div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
  
  </div>
  </div>
</div>




  <script>
    $(function() {
    var x = <%= raw @artistNames.as_json %>;
    $( "#artists" ).autocomplete({
      source: x
    });
  });
  </script>




 
</head>

<%= render :partial => 'form' %> 

app/views/concert_reviews/show.html.erb
<%- model_class = ConcertReview -%>

<img src = <%= @concertreview.image %> width= 250px style="float: left; border: solid transparent 7px">

<div class="page-header"> <em><h3><%= @concertreview.artist.name %></h3></em> Reviewed By <strong><%= @concertreview.author %></strong></div>

<dl class="dl-horizontal">

<%= simple_format(@concertreview.content.gsub(/\n/, '<br/>')) %>
<br />
</dl>